workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
    artifacts:
      - build/ios/ipa/Runner.ipa
      - //
