workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --export-method app-store
    artifacts:
      - build/ios/ipa/Runner.ipa
      - //
