name: flyweb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^7.0.2
  google_fonts: ^6.2.1

  #UI
  #cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.0.0
  flutter_speed_dial: ^7.0.0
  #flutter_native_splash: ^2.4.0
  stylish_bottom_bar: ^1.1.0
  page_transition: ^2.1.0

  #STORAGE & PERMISSION
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  #CONNECTIVITY
  http: ^1.2.1
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  rate_my_app: ^2.2.0
  store_redirect: ^2.0.2
  connectivity_plus: ^6.0.3

  #Firebase
  firebase_in_app_messaging: ^0.7.4+18
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1

  #PUSH NOTIFICATION
  onesignal_flutter: ^5.1.2

  #ADS
  google_mobile_ads: ^5.1.0

  #WEB TOOLS
  flutter_inappwebview: ^6.0.0
  #flutter_inappwebview: ^5.8.0

  # TOOLS
  device_info_plus: ^10.1.0
  global_configuration: ^2.0.0
  mobile_scanner: ^5.2.3
  app_links: ^6.1.1
  flutter_barcode_scanner: ^2.0.0

  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/flag/
    - assets/cfg/